### ISSUE TITLE
inserts random frames sometimes

### ISSUE THREAD

**Issue by nyck33** [WarrenWeckesser/numpngw#10]
I noticed that on one video of Federer and Nishikori rallying at the US Open, when I use this to put together a series of frames with numerically ascending names, it inserts random frames here and there.  It works fine with a series of frames of a burning candle and another one of a figure skater spinning.

**Comment by WarrenWeckesser** [comment]
@nyck33, if you don't provide code that I can read, there is no way that I can help you.  Even better would be a [complete, self-contained example](https://stackoverflow.com/help/minimal-reproducible-example) that I can run to try to reproduce the problem.

**Comment by nyck33** [comment]
Sorry  Warren, please use this folder of video frames:  https://drive.google.com/open?id=1Q316DSJCjTQDMifPmF-nt6HzaQoORTEI

And this line to make the gif:
```
import cv2
import numpy
import numpngw

NAME = video_dir

rgb_frames = []
for frame in frames:
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    rgb_frames.append(rgb)

path = "/gdrive/My Drive/A6-Video_Textures/videos/out/"
#os.makedirs(path, exist_ok=True)

numpngw.write_apng(NAME+'.png', rgb_frames, delay=50, use_palette=False)
```

**Comment by nyck33** [comment]
Please note that I just changed the link to the correct folder.

**Comment by WarrenWeckesser** [comment]
Thanks, but that code won't be runnable, because `frames` is not defined.  Be sure you can run the actual code that you include here, and check that when you run it, it produces the problem that you are reporting.  I can handle renaming a directory, but I need to see exactly how you load the individual frames into memory.

**Comment by nyck33** [comment]
frames is a list where the frames in the folder I linked to were read in using cv2.imread in a list comprehension
''' 
frames = [cv2.imread(f, cv2.IMREAD_UNCHANGED | cv2.IMREAD_COLOR)
                         for f in files]
'''
So it was a fairly standard list of numpy arrays.

**Comment by WarrenWeckesser** [comment]
How did you define `files` in that code snippet?  Feel free to edit the original post so that the code is a minimal and complete example.  This is important, so I can be sure that the problem is in `numpngw` and not in the code that you wrote that processes the files before calling `write_apng`.

When you say "it inserts random frames here and there", what is in the "random" frames?

**Comment by nyck33** [comment]
```
extensions = ['jpg', 'jpe', 'jp2', 'tiff', 'tif', 'png']

    search_paths = [os.path.join(image_dir, '*.' + ext) for ext in extensions]
    files = sorted(sum(map(glob, search_paths), []))
```
I can't post it as a full example because it is template code for homework and I don't want a google search by students trying to cheat leading here.  
In the following `.png` gif made with numpngw, you can see random frames of the tennis player in different positions, ie. so if the action goes from frame 1 to 10, you see it do something like 1->2->7->3->... and so on.  
https://drive.google.com/open?id=15BJeYlLon-6PTR9yoM8IOGT883mnimPE

This one of a figure skater spinning looks fine:  https://drive.google.com/open?id=171G0cc2QAsy_2W2PIAqn0tQ4uK8j9sg9

**Comment by WarrenWeckesser** [comment]
It appears that the frames in your original data are not sequenced properly.  Use your favorite image viewer to view your original PNG files one by one.  It appears that `frame0000.png`, `frame0011.png`,`frame0022.png` and `frame0033.png` are out of sequece.  That's as far as I checked--maybe that pattern continues.

**Comment by nyck33** [comment]
Sorry to waste your time Warren, I raised an issue for a possible bug in the provided template code with the course instructors in the highly ranked graduate comp sci program with lecture videos on udacity.
