### ISSUE TITLE
it would be kind for pip system if you could publish directly a wheel

### ISSUE THREAD

**Issue by stonebig** [WarrenWeckesser/numpngw#4]
````
python setup.py sdist bdist_wheel  --universal
twine upload dist/*
````

**Comment by WarrenWeckesser** [comment]
Thanks for the tip.  I'm working on getting version 0.0.5 on pypi, so I'll also try to include a wheel. (I'm having a problem with twine at the moment.)

**Comment by WarrenWeckesser** [comment]
I just uploaded a wheel: https://pypi.python.org/pypi/numpngw/0.0.6
If you use it, let me know if you find any problems.

**Comment by WarrenWeckesser** [comment]
There haven't been any problems reported for the wheel, so I'm closing this issue.
