### ISSUE TITLE
example3 doesn't work for me

### ISSUE THREAD

**Issue by gogobd** [WarrenWeckesser/numpngw#5]
Hi! I've just tried example3.py but my result looks like this:

![example3](https://user-images.githubusercontent.com/728976/32395949-9b03f290-c0e3-11e7-9a7a-5e477f0ec3c4.png)

Is that reproducible?

**Comment by WarrenWeckesser** [comment]
> Is that reproducible?

Yes!  I'm looking into it.  Thanks for reporting the problem.

**Comment by WarrenWeckesser** [comment]
I just pushed a change that should fix the problem.  I assume you are using numpy 1.13.  numpy changed the behavior of the function 'apply_along_axis', and that exposed a bug in numpngw.
