### ISSUE TITLE
What are the parameters?

### ISSUE THREAD

**Issue by nyck33** [WarrenWeckesser/numpngw#9]
I pretty much copied one of the examples:
```
numpngw.write_apng(NAME+'.png', frames, delay=50, use_palette=False)
```
but have no idea what `delay=50` is.

**Comment by WarrenWeckesser** [comment]
`delay` specifies the length of time (in milliseconds) that each frame is displayed.  The parameter is explained in the docstring, but I see that it needs a bit of editing.

**Comment by WarrenWeckesser** [comment]
I expanded the description of `delay` in the `write_apng` docstring in https://github.com/WarrenWeckesser/numpngw/commit/cf8af7638903fa1aea0e07d89837da675a23c860, so I'm closing this issue. Let me know if you more clarification.
